### ISSUE TITLE
Is there any way to specify the internal listening port as something else than 32400?

### ISSUE THREAD

**Issue by qdm12** [spritsail/plex-media-server#37]
Hi there!

Do you think there is any way to change the listening port to something else than 32400.?

The use case is to have your container plugged in a vpn client container (github.com/qdm12/gluetun) and access plex through the VPN server IP and a VPN server side port forwarded, so you cannot fiddle with Docker port mapping.

For now I can do it with:

- a reverse proxy container plugged in the vpn client as well
- with `iptables` (since a VPN client container already has NET_ADMIN capability

But it would be quite nice to just have an environment variable to change the internal listening port 😉 

Thanks!

**Comment by Adam-Ant** [comment]
Hi,
Unfortunately, Plex doesn't give us the option of changing the local listen port for the server (sources [here](https://support.plex.tv/articles/200931138-troubleshooting-remote-access/) (note LAN/Internal Port) and [here](https://forums.plex.tv/t/change-plex-media-server-port-away-from-32400/115662/5)), only the remote port for external access or using Docker's native port remapping. I do agree this would be useful, but adding iptables etc into the container is a tad out of scope, as Docker's native port mapping covers most typical use cases.

Only thing I can suggest is using our image as a basis with a FROM line and adding it into the container yourself, as we try not to have too many major breaking changes where Plex allows, but to be honest your current set up is probably less maintenance!

Sorry this wasn't the answer you were hoping for, but thanks for raising an issue!

**Comment by qdm12** [comment]
Thanks for the quick reply!

I wasn't suggesting to add iptables or a Rev proxy to your container though.

Bummer plex doesn't support such trivial feature. Especially in that niche situation with a VPN client container, it is actually needed when you get a random unique port forwarded from your VPN server provider.

But as I mentioned, I have workarounds, so no worry :+1: also Thanks for the references!
