### ISSUE TITLE
Plex pass latest (1.40.X)

### ISSUE THREAD

**Issue by jpasantos** [spritsail/plex-media-server#43]
I was attempting to upgrade container running :plexpass and all I have is a `/sbin/tini: accessing a corrupted shared library`. Rolling back to :plexpass-1.32.8.7639 fixed the issue so I would assume something stopped working on 1.40 version.

Thanks for the great docker images

**Comment by Adam-Ant** [comment]
Thanks for logging an issue. Strangely I can't seem to replicate this - the CI tests passed that point, we've got a couple of our personal Plex servers running the new version quite happily, and I've just spun up a brand new server which is also behaving!

Are you running the x86 version of the image, or the ARM one?

You could also try removing the container, deleting the image with `docker rmi spritsail/plex-media-server:plexpass` (or whichever tag you're using) and pulling fresh. Docker does checksum the image on pull, so this shouldn't change anything, but stranger things have happened! 

I'd also recommend creating a fresh server with an empty `/config` directory as a test if it's still not working - helps us narrow it down to something odd in your config, or something in the image.

**Comment by jpasantos** [comment]
Hi I deleted the container and image and downloading it fresh did in fact fix the issue so it looks like it somehow was defective on my machine. Thanks for the support
